### ISSUE TITLE
Problem forming sub objects in models

### ISSUE THREAD

**Issue by rikkouri** [isabinin/aws-apigateway-swagger-exporter#4]
The following model JSON schema fails to render correctly. It appears as if the exporting fails to render the sub 'meta' objects properties.

**Model Template:**

``` json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Error Schema",
  "type" : "object",
  "properties" : {
    "meta" : {
        "type" : "object",
        "properties" : {
            "code" : { "type" : "integer" },
            "message" : { "type" : "string" },
            "type" : { "type" : "string" }
        }
    },
    "data" : { "type" : "string" }
  }
}
```

**YAML Output:**

``` yaml
definitions:
  Error:
    type: "object"
    properties:
      meta:
        type: "object"
      data:
        type: "string"
    description: "This is a default error schema model"
```
